import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Bytebank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userName = "Joana da Silva Oliveira";
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./icon.svg" type="image/svg" />
      </head>

      <body className={`${inter.variable}`}>
      <Header 
        clientName={userName} 
      />
        <div className="containerClient"> 
          {children} 
        </div>
      </body>
    </html>
  );
}
