import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import "../styles/globals.css"
import { firaCode, inter } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Bytebank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userName = "Joana da Silva Oliveira";
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./icon.svg" type="image/svg" />
      </head>

      <body className={`${inter.variable} ${firaCode.variable}`}>
      <Header 
        clientName={userName} 
      />
        <div className="containerClient"> 
          {children} 
        </div>
      </body>
    </html>
  );
}
